name: Deploy docs

# 1. Tag and Release - on PR merge of v*-version-release
#    * Tag current version
#    * Release just tagged version
# 2. Package and Publish - on published release (from #1)
#    * Build wheel
#    * Publish to pypi
# 3. (THIS STEP) Deploy docs - on published release (from #1) (or as triggered)
#    * pip install geoips
#    * pip install plugin repo
#    * build docs with geoips/docs/build_docs.py, producing artifact
#    * deploy docs from produced artifact(s)

on:
  workflow_call:
    secrets:
      token:
        required: true

env:
  GEOIPS_DEFAULT_BRANCH: ${{ vars.GEOIPS_DEFAULT_BRANCH }} # generally 'main', for open source geoips
  DOCS_BUILD_STRATEGY: ${{ vars.DOCS_BUILD_STRATEGY }} # Current options: {'basic', 'versioned-rebuild', 'versioned-update'}
  DOCS_MIN_VERSION: ${{ vars.DOCS_MIN_VERSION }} # if not set, use all minor version families

jobs:
  print-variables:
    name: Print variables
    uses: NRLMMD-GEOIPS/geoips_ci/.github/workflows/reusable-print-variables.yaml@main

  define-matrix:
    runs-on: ${{ vars.RUNNER }}
    name: "Determine which iterations of versions of docs should be built and deployed"
    outputs:
      include: ${{ steps.set-matrix.outputs.include }}
    steps:
      - name: Checkout current package current branch (version search)
        if: ${{ env.DOCS_BUILD_STRATEGY == 'versioned-rebuild' || env.DOCS_BUILD_STRATEGY == 'versioned-update' }}
        uses: actions/checkout@v6
        with:
          fetch-tags: true
          token: ${{ secrets.token }}
          path: current_repo_current_branch

      - name: Define versions
        id: set-matrix
        run: |
          if [[ "$DOCS_BUILD_STRATEGY" == "versioned-rebuild" ]]; then
            # First include latest default as dev, then, loop through all minor version
            # families with non-pre releases at or above a min, target most recent point
            include_contents="{\"current-ref\":\"$GEOIPS_DEFAULT_BRANCH\",\"dir-name\":\"dev\"}"
            candidate_versions=$(
              git -C current_repo_current_branch tag |
                grep -E "^[0-9]+\.[0-9]+\.[0-9]+$" |
                grep -oE "^[0-9]+\.[0-9]+" |
                sort -u || true
            )
            echo "Found the following minor version families with stable releases..."
            echo "$candidate_versions"
            echo "...now comparing against minimum."
            IFS='.' read -a min_version_parts <<< "${DOCS_MIN_VERSION:-}"
            while read -r this_version; do
              [[ -z "$this_version" ]] && continue # handles case of no candidate versions
              IFS='.' read -a this_version_parts <<< "$this_version"
              if [[ -z "${DOCS_MIN_VERSION:-}" || "${this_version_parts[0]}" -gt "${min_version_parts[0]}" || ("${this_version_parts[0]}" == "${min_version_parts[0]}" && "${this_version_parts[1]}" -ge "${min_version_parts[1]}") ]]; then
                latest_matching_ref=$(git -C current_repo_current_branch tag | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | grep -E "^${this_version}\.[0-9]+$" | sort -t "." -n -k3,3 -r | head -n 1)
                include_contents="$include_contents,{\"current-ref\":\"$latest_matching_ref\",\"dir-name\":\"v$this_version\"}"
              fi
            done <<< "$candidate_versions"
            echo "Building multiple versions as defined by..."
            echo "$include_contents"
            echo "include=[$include_contents]" >> "$GITHUB_OUTPUT"
          elif [[ "$DOCS_BUILD_STRATEGY" == "versioned-update" ]]; then
            if [[ "${GITHUB_REF}" == "refs/tags/"* && ${GITHUB_REF:10} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              this_version_dir="v"$(awk -F'.' '{print $1"."$2}' <<< "${GITHUB_REF:10}")
              echo "Building $GEOIPS_DEFAULT_BRANCH to /dev and current ref to $this_version_dir..."
              echo "include=[{\"current-ref\":\"$GEOIPS_DEFAULT_BRANCH\",\"dir-name\":\"dev\"},{\"current-ref\":\"${GITHUB_REF:10}\",\"dir-name\":\"$this_version_dir\"}]" >> "$GITHUB_OUTPUT"
            else
              # This is not a non-pre tagged release, so just build default main to dev
              echo "Building $GEOIPS_DEFAULT_BRANCH to /dev..."
              echo "include=[{\"current-ref\":\"$GEOIPS_DEFAULT_BRANCH\",\"dir-name\":\"dev\"}]" >> "$GITHUB_OUTPUT"
            fi
          else
            # For "$DOCS_BUILD_STRATEGY" == "basic", but is otherwise general default (including
            # the build strategy being unspecified): Build triggering ref as "/docs"
            echo "Building current ref to /docs..."
            echo 'include=[{"current-ref":"","dir-name":"docs"}]' >> "$GITHUB_OUTPUT"
          fi

  produce-docs-artifacts:
    runs-on: ${{ vars.RUNNER }}
    needs: define-matrix
    name: "Build docs for later upload to GitHub Pages"
    strategy:
      matrix:
        include: ${{ fromJSON(needs.define-matrix.outputs.include) }}
    permissions:
      contents: write
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5 # While not latest, v5 is known to work
        with:
          python-version: "3.11"
          check-latest: true

      - name: Update pip
        run: pip install --upgrade pip

      - name: Checkout geoips repo default branch
        uses: actions/checkout@v6
        with:
          repository: ${{ vars.GEOIPS_ORGANIZATION }}/geoips
          ref: ${{ vars.GEOIPS_DEFAULT_BRANCH }}
          token: ${{ secrets.token }}
          path: geoips_default_branch

      - name: pip install geoips_default_branch[doc,lint,test]
        run: |
          which pip
          pip uninstall -y geoips
          # Include test dependency for full documentation
          # lint required for pink (rst linting)
          pip install "$PWD/geoips_default_branch[doc,lint,test]"
          ret=$?
          echo "${ret}"
          python -c "import geoips; print(geoips.__version__)"

      - name: Checkout current plugin current branch
        uses: actions/checkout@v6
        with:
          fetch-tags: true
          ref: ${{ matrix.current-ref }} # Note that this falls back to default (trigger reference) if empty
          token: ${{ secrets.token }}
          path: current_repo_current_branch

      - name: Extract repository name
        id: repo-name
        run: |
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | sed "s,$GITHUB_REPOSITORY_OWNER/,,")
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Determine package name
        id: package-name
        env:
          REPO_NAME: ${{ steps.repo-name.outputs.repo_name }}
        run: |
          if [[ "$REPO_NAME" == "template_basic_plugin" ]]; then
            echo "package_name=my_package" >> $GITHUB_OUTPUT
          else
            echo "package_name=$REPO_NAME" >> $GITHUB_OUTPUT
          fi

      - name: pip install geoips plugin repo
        env:
          PACKAGE_NAME: ${{ steps.package-name.outputs.package_name }}
          REPO_NAME: ${{ steps.repo-name.outputs.repo_name }}
        run: |
          which pip
          pip uninstall -y "$PACKAGE_NAME"
          if [[ "$REPO_NAME" == "geoips" ]]; then
            # if this is geoips proper, need old version installed for doc building
            pip install -v "$PWD/current_repo_current_branch[doc,lint,test]"
            ret=$?
          else
            pip install -v "$PWD/current_repo_current_branch"
            ret=$?
          fi
          echo "${ret}"
          python -c "import $PACKAGE_NAME; print($PACKAGE_NAME.__version__)"

      - name: create_plugin_registries
        run: |
          echo "create plugin registries"
          export GEOIPS_PACKAGES_DIR="."
          export GEOIPS_OUTDIRS=""
          export GEOIPS_TESTDATA_DIR=""
          which create_plugin_registries
          create_plugin_registries
          ret=$?
          echo "${ret}"

      - name: Run build docs
        env:
          PACKAGE_NAME: ${{ steps.package-name.outputs.package_name }}
        run: |
          which pip
          echo "Build html docs"

          # Ie, get 'recenter_tc' out of 'NRLMMD-GEOIPS/recenter_tc'
          curr_repo=`echo "$GITHUB_REPOSITORY" | sed "s,$GITHUB_REPOSITORY_OWNER/,,"`
          # Call build_docs.py from the geoips default branch
          # Pass in
          #   the path to the current plugin repo,
          #   the name of the current repo,
          #   the path to output the built html docs files
          #   the path to the docs template directory in the geoips default branch.
          # If we are specifically "template_basic_plugin" repo, then we must use
          # my_package as the package name.  Otherwise the package name matches
          # the plugin name.
          run_on_package=$curr_repo
          if [[ "$curr_repo" == "template_basic_plugin" ]]; then
            run_on_package=my_package
          fi
          export GEOIPS_PACKAGES_DIR="."
          export GEOIPS_OUTDIRS=""
          export GEOIPS_TESTDATA_DIR="" # necessary for GeoIPS to be importable for the docs to build. Just has to be set to *something*
          # If we are on geoips proper, use *current* branch rather than default to build
          # (this is to avoid pre- and post- v2.0 incompatibilities)
          if [[ "$curr_repo" == "geoips" ]]; then
            docs_builder="current_repo_current_branch"
          else
            docs_builder="geoips_default_branch"
          fi
          ln -s "./$docs_builder" ./geoips # the CLI *requires* the geoips folder to be named "geoips" so soft linking here
          python3 ./geoips/docs/build_docs.py \
            --geoips-docs-path ./geoips/docs \
            --output-dir "./current_repo_current_branch/docs/build/sphinx/html" \
            --repo-path ./current_repo_current_branch \
            "$curr_repo"

      - name: Upload docs (if GitHub Hosted)
        uses: actions/upload-artifact@v7 # GHES requires a downgrade to v3.2.2 (no change to arguments)
        with:
          name: ${{ matrix.dir-name }}
          path: current_repo_current_branch/docs/build/sphinx/html
          retention-days: 1

  deploy-docs-artifacts:
    runs-on: ${{ vars.RUNNER }}
    needs: produce-docs-artifacts
    name: "Deploy collected docs to GitHub Pages"
    permissions:
      contents: write
    steps:
      - name: Setup Python
        if: ${{ env.DOCS_BUILD_STRATEGY == 'versioned-rebuild' || env.DOCS_BUILD_STRATEGY == 'versioned-update' }}
        uses: actions/setup-python@v5 # While not latest, v5 is known to work
        with:
          python-version: "3.11"
          check-latest: true

      - name: Update pip
        if: ${{ env.DOCS_BUILD_STRATEGY == 'versioned-rebuild' || env.DOCS_BUILD_STRATEGY == 'versioned-update' }}
        run: pip install --upgrade pip

      - name: Checkout ghpages branch
        uses: actions/checkout@v6
        with:
          ref: ghpages
          token: ${{ secrets.token }}
          path: ghpages_repo

      - name: Checkout default for ancilary files (for versioned)
        if: ${{ env.DOCS_BUILD_STRATEGY == 'versioned-rebuild' || env.DOCS_BUILD_STRATEGY == 'versioned-update' }}
        uses: actions/checkout@v6
        with:
          repository: ${{ vars.GEOIPS_ORGANIZATION }}/geoips
          ref: ${{ vars.GEOIPS_DEFAULT_BRANCH }}
          token: ${{ secrets.token }}
          path: geoips_default_branch

      - name: pip install geoips_default_branch[doc]
        if: ${{ env.DOCS_BUILD_STRATEGY == 'versioned-rebuild' || env.DOCS_BUILD_STRATEGY == 'versioned-update' }}
        run: |
          which pip
          pip uninstall -y geoips
          # Needed for anciliar file builds
          pip install "$PWD/geoips_default_branch[doc]"
          ret=$?
          echo "${ret}"
          python -c "import geoips; print(geoips.__version__)"

      - name: Reset ghpages branch state (/docs only)
        if: ${{ env.DOCS_BUILD_STRATEGY == '' || env.DOCS_BUILD_STRATEGY == 'basic' }}
        run: |
          cd ./ghpages_repo
          rm -rf docs

      - name: Reset ghpages branch state (full)
        if: ${{ env.DOCS_BUILD_STRATEGY == 'versioned-rebuild' }}
        run: |
          cd ./ghpages_repo
          # remove all git-tracked files
          git ls-files | xargs -r rm
          # remove all directories that had contained git-tracked files
          git ls-tree --name-only -d -r -z HEAD | sort -rz | xargs -0 rmdir

      - name: Reset ghpages branch state (partial)
        if: ${{ env.DOCS_BUILD_STRATEGY == 'versioned-update' }}
        run: |
          cd ./ghpages_repo
          rm -rf dev

      - name: Download all docs builds (if GitHub Hosted)
        uses: actions/download-artifact@v8  # GHES requires a downgrade to v3.2.2 (no change to arguments)
        with:
          path: ghpages_repo

      - name: Create support files (/docs only)
        if: ${{ env.DOCS_BUILD_STRATEGY == '' || env.DOCS_BUILD_STRATEGY == 'basic' }}
        run: |
          cd ./ghpages_repo
          touch docs/.nojekyll

      - name: Create all ancilary and support files (for full branch)
        if: ${{ env.DOCS_BUILD_STRATEGY == 'versioned-rebuild' }}
        env:
          UNVERSIONED_URL_STRATEGY: ${{ vars.UNVERSIONED_URL_STRATEGY }}
          PACKAGE_BASE_URL: ${{ vars.PACKAGE_BASE_URL }}
        run: |
          cd ./ghpages_repo
          # Copy gitignore, DISTRIBUTION, LICENSE, and workflows from main repo
          cp ../geoips_default_branch/.gitignore .
          cp ../geoips_default_branch/DISTRIBUTION .
          cp ../geoips_default_branch/LICENSE .
          cp -r ../geoips_default_branch/.github .
          # Create ghpages README
          echo -e "## GitHub Pages deployment branch\n\nThis branch is for docs deployment only, and is not intended to be interacted with directly." > README.md
          # Create nojekyll
          touch .nojekyll
          # Update versions control file(s)
          python3 ../geoips_default_branch/docs/create_support_files.py --scan-dir=. \
            --output-dir=. --create-version-file --create-stable-symlink \
            --base-url="$PACKAGE_BASE_URL"
          # Handle options for unversioned doc paths
          if [[ "$UNVERSIONED_URL_STRATEGY" == "ignore" ]]; then
            echo "Creating index.html redirect to stable, letting unversioned paths 404 out"
            python3 ../geoips_default_branch/docs/create_support_files.py --output-dir=. \
              --create-index-redirect
          elif [[ "$UNVERSIONED_URL_STRATEGY" == "redirect" ]]; then
            echo "Creating index.html redirect to stable and 404.html with dynamic JS redirect"
            python3 ../geoips_default_branch/docs/create_support_files.py --output-dir=. \
              --create-index-redirect --create-404-redirect
          else
            echo "Copying stable to top-level/unversioned paths"
            cp -r stable/* .
          fi

      - name: Update support files (partial)
        if: ${{ env.DOCS_BUILD_STRATEGY == 'versioned-update' }}
        env:
          UNVERSIONED_URL_STRATEGY: ${{ vars.UNVERSIONED_URL_STRATEGY }}
          PACKAGE_BASE_URL: ${{ vars.PACKAGE_BASE_URL }}
        run: |
          cd ./ghpages_repo
          # Update versions control file(s)
          python3 ../geoips_default_branch/docs/create_support_files.py --scan-dir=. \
            --output-dir=. --create-version-file --create-stable-symlink \
            --base-url=$PACKAGE_BASE_URL
          # Handle options for unversioned doc paths
          if [[ "$UNVERSIONED_URL_STRATEGY" == "copy" ]]; then
            echo "Copying stable to top-level/unversioned paths"
            cp -r stable/* .
          elif [[ "$UNVERSIONED_URL_STRATEGY" == "ignore" ]]; then
            echo "Creating index.html redirect to stable, letting unversioned paths 404 out"
            python3 ../geoips_default_branch/docs/create_support_files.py --output-dir=. \
              --create-index-redirect
          elif [[ "$UNVERSIONED_URL_STRATEGY" == "redirect" ]]; then
            echo "Creating index.html redirect to stable and 404.html with dynamic JS redirect"
            python3 ../geoips_default_branch/docs/create_support_files.py --output-dir=. \
              --create-index-redirect --create-404-redirect
          else
            echo "Leaving current unversioned URL behavior unchanged"
          fi

      - name: Push to ghpages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Configuring Git for authentication..."
          # Use the GITHUB_TOKEN for authentication on github.com
          # This replaces any https://github.com/ URL with an authenticated one
          GH_HOST=$(echo "$GITHUB_SERVER_URL" | sed 's#^https://##')
          git config --global url."https://x-access-token:$GITHUB_TOKEN@${GH_HOST}/".insteadOf "https://${GH_HOST}/"

          # Set identity to a commonly used "bot" like value, will give us a neat github actions logo in our git commit history
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Create commit and push it
          cd ./ghpages_repo
          git add .
          if git diff --cached --quiet; then
            echo "No GitHub Pages changes to commit."
            exit 0
          fi
          git commit -m "sphinx html for github pages"
          git push origin ghpages
